### PR TITLE
Move credential checks into the AzureConnection#authenticate

### LINKED ISSUE #312: running inspec check on a profile that references the latest version of the resource pack fails
Previously when running inspec check (or inspec archive) on a profile that depended on the inspec azure resource pack it would work without any errors. When running check or archive on a profile that depends on the latest version of the resource pack it fails because the azure backed requires environment variables to be set.

```
steveb@chef-x360:[cloud_scans]$ grep url test-profile-azure-level-2/inspec.yml
    url: https://github.com/inspec/inspec-azure/archive/v1.16.0.tar.gz
steveb@chef-x360:[cloud_scans]$ grep url test-profile-azure-level-1/inspec.yml
    url: https://github.com/inspec/inspec-azure/archive/v1.32.1.tar.gz


steveb@chef-x360:[cloud_scans]$ inspec check test-profile-azure-level-2/
W, [2020-09-30T20:21:35.483584 #400465]  WARN -- : Control sec-azure-control-1 has no tests defined
W, [2020-09-30T20:21:35.483626 #400465]  WARN -- : Control sec-azure-control-2 has no descriptions
W, [2020-09-30T20:21:35.483638 #400465]  WARN -- : Control sec-azure-control-2 has no tests defined
W, [2020-09-30T20:21:35.483647 #400465]  WARN -- : Control sec-azure-control-3 has no descriptions
W, [2020-09-30T20:21:35.483665 #400465]  WARN -- : Control sec-azure-control-3 has no tests defined
W, [2020-09-30T20:21:35.483674 #400465]  WARN -- : Control sec-azure-control-4 has no descriptions
W, [2020-09-30T20:21:35.483683 #400465]  WARN -- : Control sec-azure-control-4 has no tests defined
Location :   test-profile-azure-level-2/
Profile :    test-profile-azure-level2
Controls :   4
Timestamp :  2020-09-30T20:21:35+01:00
Valid :      true

 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:6: Control sec-azure-control-1 has no tests defined
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:31: Control sec-azure-control-2 has no descriptions
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:31: Control sec-azure-control-2 has no tests defined
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:47: Control sec-azure-control-3 has no descriptions
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:47: Control sec-azure-control-3 has no tests defined
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:65: Control sec-azure-control-4 has no descriptions
 !  test-profile-azure-level-2/controls/sec_1_50_01.rb:65: Control sec-azure-control-4 has no tests defined

Summary:     0 errors, 7 warnings

steveb@chef-x360:[cloud_scans]$ inspec check test-profile-azure-level-1/
[2020-09-30T20:21:41+01:00] WARN: DEPRECATION: `azurerm_resource_groups` uses the new resource `azure_resource_groups` under the hood. azurerm_resource_groups will be deprecated soon and it is advised to switch to the fully backward compatible new resource. Please see the documentation for the additional features available.
Traceback (most recent call last):
        31: from /opt/chef-workstation/bin/inspec:363:in `<main>'
        30: from /opt/chef-workstation/bin/inspec:363:in `load'
        29: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.19.0/bin/inspec:11:in `<top (required)>'
        28: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/base_cli.rb:35:in `start'
        27: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        26: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        25: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/cli.rb:108:in `check'
        22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:425:in `check'
        21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:455:in `controls_count'
        20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:196:in `params'
        19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:612:in `load_params'
        18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:619:in `load_checks_params'
        17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:205:in `collect_tests'
        16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:205:in `each'
        15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:209:in `block in collect_tests'
        14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:154:in `load_control_file'
        13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:170:in `load_with_context'
        12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:170:in `instance_eval'
        11: from test-profile-azure-level-1/controls/sec_1_50_01.rb:2:in `load_with_context'
        10: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:252:in `block (2 levels) in add_registry_methods'
         9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:252:in `new'
         8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:118:in `initialize'
         7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:54:in `supersuper_initialize'
         6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:119:in `block in initialize'
         5: from libraries/azure_resource_groups.rb:77:in `initialize'
         4: from libraries/azure_resource_groups.rb:24:in `initialize'
         3: from libraries/azure_generic_resources.rb:16:in `initialize'
         2: from libraries/azure_backend.rb:48:in `initialize'
         1: from libraries/azure_backend.rb:48:in `new'
libraries/backend/azure_connection.rb:62:in `initialize': The following must be set in the Environment: [:tenant_id, :client_id, :client_secret, :subscription_id].Provided: {:tenant_id=>nil, :client_id=>nil, :client_secret=>nil, :subscription_id=>nil}
        30: from /opt/chef-workstation/bin/inspec:363:in `<main>'
        29: from /opt/chef-workstation/bin/inspec:363:in `load'
        28: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-bin-4.19.0/bin/inspec:11:in `<top (required)>'
        27: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/base_cli.rb:35:in `start'
        26: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        25: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        24: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        23: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        22: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/cli.rb:108:in `check'
        21: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:425:in `check'
        20: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:455:in `controls_count'
        19: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:196:in `params'
        18: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:612:in `load_params'
        17: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:619:in `load_checks_params'
        16: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:205:in `collect_tests'
        15: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:205:in `each'
        14: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile.rb:209:in `block in collect_tests'
        13: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:154:in `load_control_file'
        12: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:170:in `load_with_context'
        11: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:170:in `instance_eval'
        10: from test-profile-azure-level-1/controls/sec_1_50_01.rb:2:in `load_with_context'
         9: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:252:in `block (2 levels) in add_registry_methods'
         8: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/profile_context.rb:252:in `new'
         7: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:118:in `initialize'
         6: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:54:in `supersuper_initialize'
         5: from /opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/inspec-core-4.19.0/lib/inspec/resource.rb:119:in `block in initialize'
         4: from libraries/azure_resource_groups.rb:77:in `initialize'
         3: from libraries/azure_resource_groups.rb:24:in `initialize'
         2: from libraries/azure_generic_resources.rb:16:in `initialize'
         1: from libraries/azure_backend.rb:47:in `initialize'
libraries/azure_backend.rb:52:in `rescue in initialize': HTTP Client Error.The following must be set in the Environment: [:tenant_id, :client_id, :client_secret, :subscription_id].
Provided: {:tenant_id=>nil, :client_id=>nil, :client_secret=>nil, :subscription_id=>nil}

```

### PR DESCRIPTION
**Pull request by omerdemirok**
Signed-off-by: Omer Demirok <odemirok@chef.io>

### Description

- Move credential checks into the `AzureConnection#authenticate` method to enable `inspec check` pass
- Update Rakefile regarding the credential checks
- Fix `azure_resource_group#to_s` method

### Issues Resolved

Fixes #312 

### Check List

- [ ] New functionality includes tests
- [x] All tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

File: libraries/backend/azure_connection.rb [hunk 1]
```diff
@@ -123,6 +117,12 @@ def rest_get_call(url, params = {})
   # https://docs.microsoft.com/en-us/rest/api/azure/
   #
   def authenticate(resource)
+    # Validate the presence of credentials.
+    unless @credentials.values.compact.delete_if(&:empty?).size == 4
+      raise HTTPClientError::MissingCredentials, 'The following must be set in the Environment:'\
+        " #{@credentials.keys}.\n"\
+        "Provided: #{@credentials}"
```
Comment (rmoles) [inline libraries/backend/azure_connection.rb:124]: This looks like this will currently output the key and value. Debating whether it's better to avoid outputting the values and just output which keys they have set.

Comment (omerdemirok) [reply libraries/backend/azure_connection.rb:124]: Can do, good idea.

Comment (omerdemirok) [reply libraries/backend/azure_connection.rb]: This should be fixed now.

**Review by rmoles — APPROVED** [review]
Thanks @omerdemirok
