### PR TITLE
Fix environment parameters

### LINKED ISSUE #289: Bad URL is used when endpoint is set for non-default Azure Cloud
# Describe the problem
I set endpoint to 'azure_china_cloud' in order to try InSpec on Azure China, but the control fails due to REST API error.

`inspec exec` output as below: 
......
 Unsuccessful HTTP request to Azure REST API.
     HTTP 400.
     {:error=>"invalid_resource", :error_description=>"AADSTS500011: The resource principal named **https://management.chinacloudapi.cnsubscriptions** was not found in the tenant named 10f43eaa-0c68-461f-ba9e-0c5....

## Possible Solution

line 109 in libraries/backend/azure_environment.rb, the url should end with slash. Similar issues may exist for other non-default environments.

### PR DESCRIPTION
**Pull request by omerdemirok**
Signed-off-by: Omer Demirok <odemirok@chef.io>

### Description

Check forward slashes when constructing a url.

### Issues Resolved

Fixes #289 🤞 

### Check List

- [ ] New functionality includes tests
- [x] All tests pass
- [x] `rake lint` passes
- [x] All commits have been signed-off for the Developer Certificate of Origin. See <https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco>

### CODE REVIEW

File: libraries/azure_backend.rb [hunk 1]
```diff
@@ -303,7 +307,13 @@ def get_api_version(provider, resource_type, api_version_status = 'latest')
 
     # If the resource manager api version is updated earlier, use that.
     api_version_mgm = @resource_manager_endpoint_api || @azure.resource_manager_endpoint_api_version
-    url = "#{@azure.resource_manager_endpoint_url}subscriptions/#{@azure.credentials[:subscription_id]}/providers/#{provider}"
+    # url = "#{@azure.resource_manager_endpoint_url}subscriptions/#{@azure.credentials[:subscription_id]}/providers/#{provider}"
```
Comment (rmoles) [inline libraries/azure_backend.rb:310]: This line can probably be removed

**Review by rmoles — APPROVED** [review]
A comment could be removed, but apart from that looks good to go.
